import{a as f,S as M,i as a}from"./assets/vendor-DaKTFKe4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const $="56131780-53206f25f9992fd25cf079e43";f.defaults.baseURL="https://pixabay.com/api/";async function m(o,t=1){return(await f.get("",{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more-btn");let B=new M(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:i,largeImageURL:c,tags:e,likes:r,views:s,comments:v,downloads:q})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${c}">
        <img class="gallery-image" src="${i}" alt="${e}" />
      </a>
      <div class="info-container">
        <p class="info-item"><b>Likes</b><span>${r}</span></p>
        <p class="info-item"><b>Views</b><span>${s}</span></p>
        <p class="info-item"><b>Comments</b><span>${v}</span></p>
        <p class="info-item"><b>Downloads</b><span>${q}</span></p>
      </div>
    </li>`).join("");p.insertAdjacentHTML("beforeend",t),B.refresh()}function P(){p.innerHTML=""}function L(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}function w(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}const S=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let l="",n=1,u=0;S.addEventListener("submit",x);O.addEventListener("click",H);async function x(o){if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),!!l){n=1,P(),d(),L();try{const t=await m(l,n);if(u=t.totalHits,t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),u<=15?(d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch{a.error({message:"Something went wrong. Please try again later."})}finally{b(),S.reset()}}}async function H(){n+=1,d(),L();try{const o=await m(l,n);g(o.hits),R(),n*15>=u?(d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch{a.error({message:"Failed to load more images."})}finally{b()}}function R(){const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
